backend:
  name: github
  repo: smldms/web
  branch: main
  publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Categories",
          name: "categories",
          widget: "select",
          multiple: true,
          options:
            [
              "generative-art",
              "runtime-art",
              "post-photography",
              "platform",
              "dj-set",
            ],
        }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          allow_add: true,
          field: { label: "Image", name: "image", widget: "image" }
        }
      - {
          label: "YouTube Video",
          name: "youtubeVideo",
          widget: "string",
          required: false,
          hint: "Ajoute l'URL complète d'une vidéo YouTube"
        }
      - {
          label: "External Link",
          name: "externalLink",
          widget: "string",
          required: false,
          hint: "Ajoute un lien externe pour ce projet"
        }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - {
          label: "P5.js Code",
          name: "p5jsCode",
          widget: "text",
          required: false,
          hint: "Collez ici le code JavaScript de votre sketch P5.js"
        }


  - name: "soundtracks"
    label: "Sound Project"
    folder: "src/content/soundtracks"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { 
          label: "Type", 
          name: "type", 
          widget: "select", 
          options: ["track", "dj-set", "collaboration"] 
        }
      - { 
          label: "URL Soundcloud", 
          name: "soundcloudUrl", 
          widget: "string", 
          required: false,
          hint: "Obligatoire pour les tracks et collaborations, optionnel pour les DJ sets"
        }
      - { 
          label: "URL YouTube", 
          name: "youtubeUrl", 
          widget: "string", 
          required: false,
          hint: "Optionnel pour tous les types, mais recommandé pour les DJ sets"
        }
      - { label: "Image de couverture", name: "coverImage", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["electronic"] }
      - { label: "Mis en avant", name: "featured", widget: "boolean", default: false }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Paramètres"
    files:
      - label: "Configuration Sound"
        name: "sound-config"
        file: "src/content/settings/sound.json"
        fields:
          - { label: "Titre de la page", name: "pageTitle", widget: "string", default: "SOUND" }
          - { label: "Description de la page", name: "pageDescription", widget: "string" }
          - { label: "Image d'arrière-plan", name: "backgroundImage", widget: "image" }
          - { label: "Titre section Tracks", name: "tracksTitle", widget: "string", default: "Tracks" }
          - { label: "Titre section DJ Sets", name: "djSetsTitle", widget: "string", default: "DJ Sets" }
          - { label: "Titre section Collaborations", name: "collaborationsTitle", widget: "string", default: "Collaborations" }
