backend:
  name: github
  repo: smldms/web
  branch: main
  publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Catégories", name: "categories", widget: "list", default: ["generative-art"] }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image principale", name: "coverImage", widget: "image" }
      - { label: "Galerie d'images", name: "gallery", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
      - { label: "Texte enrichi", name: "body", widget: "markdown" }
      - { label: "Lien externe", name: "externalLink", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      # - { label: "Visible", name: "visible", widget: "boolean", default: true }